In [4]:
pip install ucimlrepo

Requirement already satisfied: ucimlrepo in c:\users\juded\anaconda3\lib\site-packages (0.0.7)
Requirement already satisfied: pandas>=1.0.0 in c:\users\juded\anaconda3\lib\site-packages (from ucimlrepo) (2.2.3)
Requirement already satisfied: certifi>=2020.12.5 in c:\users\juded\anaconda3\lib\site-packages (from ucimlrepo) (2025.6.15)
Requirement already satisfied: numpy>=1.26.0 in c:\users\juded\anaconda3\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\juded\anaconda3\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\juded\anaconda3\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\juded\anaconda3\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\juded\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [16]:
import pandas as pd

# Load the raw hypothyroid data
df = pd.read_csv("../data/hypothyroid.csv", header=None)

# Show top rows
df.head()

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,age,sex,on thyroxine,query on thyroxine,on antithyroid medication,sick,pregnant,thyroid surgery,I131 treatment,query hypothyroid,...,TT4 measured,TT4,T4U measured,T4U,FTI measured,FTI,TBG measured,TBG,referral source,binaryClass
1,41,F,f,f,f,f,f,f,f,f,...,t,125,t,1.14,t,109,f,?,SVHC,P
2,23,F,f,f,f,f,f,f,f,f,...,t,102,f,?,f,?,f,?,other,P
3,46,M,f,f,f,f,f,f,f,f,...,t,109,t,0.91,t,120,f,?,other,P
4,70,F,t,f,f,f,f,f,f,f,...,t,175,f,?,f,?,f,?,other,P

In [18]:
print(df.columns.tolist())

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]

In [23]:
import pandas as pd

df = pd.read_csv("../data/hypothyroid.csv", header=0)

df.head()

,age,sex,on thyroxine,query on thyroxine,on antithyroid medication,sick,pregnant,thyroid surgery,I131 treatment,query hypothyroid,...,TT4 measured,TT4,T4U measured,T4U,FTI measured,FTI,TBG measured,TBG,referral source,binaryClass
0,41,F,f,f,f,f,f,f,f,f,...,t,125,t,1.14,t,109,f,?,SVHC,P
1,23,F,f,f,f,f,f,f,f,f,...,t,102,f,?,f,?,f,?,other,P
2,46,M,f,f,f,f,f,f,f,f,...,t,109,t,0.91,t,120,f,?,other,P
3,70,F,t,f,f,f,f,f,f,f,...,t,175,f,?,f,?,f,?,other,P
4,70,F,f,f,f,f,f,f,f,f,...,t,61,t,0.87,t,70,f,?,SVI,P

In [24]:
print(df.columns.tolist())

['age', 'sex', 'on thyroxine', 'query on thyroxine', 'on antithyroid medication', 'sick', 'pregnant', 'thyroid surgery', 'I131 treatment', 'query hypothyroid', 'query hyperthyroid', 'lithium', 'goitre', 'tumor', 'hypopituitary', 'psych', 'TSH measured', 'TSH', 'T3 measured', 'T3', 'TT4 measured', 'TT4', 'T4U measured', 'T4U', 'FTI measured', 'FTI', 'TBG measured', 'TBG', 'referral source', 'binaryClass']

In [64]:
df.replace('?', pd.NA, inplace=True)

In [30]:
df.isnull().sum()

age                             1
sex                           150
on thyroxine                    0
query on thyroxine              0
on antithyroid medication       0
sick                            0
pregnant                        0
thyroid surgery                 0
I131 treatment                  0
query hypothyroid               0
query hyperthyroid              0
lithium                         0
goitre                          0
tumor                           0
hypopituitary                   0
psych                           0
TSH measured                    0
TSH                           369
T3 measured                     0
T3                            769
TT4 measured                    0
TT4                           231
T4U measured                    0
T4U                           387
FTI measured                    0
FTI                           385
TBG measured                    0
TBG                          3772
referral source                 0
binaryClass                     0
dtype: int64

In [33]:
df.drop(columns=['TBG'], inplace=True)

KeyError: "['TBG'] not found in axis"

In [37]:
if 'TBG' in df.columns:
    df.drop(columns=['TBG'], inplace=True)

num_cols = ['age', 'TSH', 'T3', 'TT4', 'T4U', 'FTI']
for col in num_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

for col in num_cols:
    median_val = df[col].median()
    df[col].fillna(median_val, inplace=True)

print(df[num_cols].isnull().sum())

age    0
TSH    0
T3     0
TT4    0
T4U    0
FTI    0
dtype: int64

C:\Users\juded\AppData\Local\Temp\ipykernel_14744\3737841504.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(median_val, inplace=True)

In [40]:
for col in num_cols:
    median_val = df[col].median()
    df[col] = df[col].fillna(median_val)

In [43]:
keep_cols = [
    'age', 'sex',
    'on thyroxine', 'query on thyroxine', 'on antithyroid medication',
    'sick', 'pregnant', 'thyroid surgery', 'I131 treatment',
    'query hypothyroid', 'query hyperthyroid', 'lithium',
    'goitre', 'tumor', 'hypopituitary', 'psych',
    'TSH', 'T3', 'TT4', 'T4U', 'FTI',
    'binaryClass'
]
df = df[keep_cols]

In [46]:
# Convert sex: M = 0, F = 1
df['sex'] = df['sex'].map({'M': 0, 'F': 1})

# Convert all t/f to 1/0
bool_cols = [
    'on thyroxine', 'query on thyroxine', 'on antithyroid medication',
    'sick', 'pregnant', 'thyroid surgery', 'I131 treatment',
    'query hypothyroid', 'query hyperthyroid', 'lithium',
    'goitre', 'tumor', 'hypopituitary', 'psych'
]
for col in bool_cols:
    df[col] = df[col].map({'t': 1, 'f': 0})

# Convert target class: N = 0, P = 1
df['binaryClass'] = df['binaryClass'].map({'N': 0, 'P': 1})

In [50]:
# Replacing 'f' with 0, 't' with 1 before converting to numeric
df.replace({'f': 0, 't': 1}, inplace=True)

In [56]:
import pandas as pd

df = pd.read_csv("../data/hypothyroid.csv", header=1
                )

df.head()

,41,F,f,f.1,f.2,f.3,f.4,f.5,f.6,f.7,...,t.2,125,t.3,1.14,t.4,109,f.14,?,SVHC,P
0,23,F,f,f,f,f,f,f,f,f,...,t,102,f,?,f,?,f,?,other,P
1,46,M,f,f,f,f,f,f,f,f,...,t,109,t,0.91,t,120,f,?,other,P
2,70,F,t,f,f,f,f,f,f,f,...,t,175,f,?,f,?,f,?,other,P
3,70,F,f,f,f,f,f,f,f,f,...,t,61,t,0.87,t,70,f,?,SVI,P
4,18,F,t,f,f,f,f,f,f,f,...,t,183,t,1.3,t,141,f,?,other,P

In [58]:
print(df.columns.tolist())

['41', 'F', 'f', 'f.1', 'f.2', 'f.3', 'f.4', 'f.5', 'f.6', 'f.7', 'f.8', 'f.9', 'f.10', 'f.11', 'f.12', 'f.13', 't', '1.3', 't.1', '2.5', 't.2', '125', 't.3', '1.14', 't.4', '109', 'f.14', '?', 'SVHC', 'P']

In [61]:
columns = ['age', 'sex', 'on thyroxine', 'query on thyroxine', 'on antithyroid medication', 'sick',
           'pregnant', 'thyroid surgery', 'I131 treatment', 'query hypothyroid', 'query hyperthyroid',
           'lithium', 'goitre', 'tumor', 'hypopituitary', 'psych', 'TSH measured', 'TSH',
           'T3 measured', 'T3', 'TT4 measured', 'TT4', 'T4U measured', 'T4U',
           'FTI measured', 'FTI', 'TBG measured', 'TBG', 'referral source', 'binaryClass']

df = pd.read_csv("../data/hypothyroid.csv", header=None, names=columns, skiprows=1)

In [63]:
df.head()

,age,sex,on thyroxine,query on thyroxine,on antithyroid medication,sick,pregnant,thyroid surgery,I131 treatment,query hypothyroid,...,TT4 measured,TT4,T4U measured,T4U,FTI measured,FTI,TBG measured,TBG,referral source,binaryClass
0,41,F,f,f,f,f,f,f,f,f,...,t,125,t,1.14,t,109,f,?,SVHC,P
1,23,F,f,f,f,f,f,f,f,f,...,t,102,f,?,f,?,f,?,other,P
2,46,M,f,f,f,f,f,f,f,f,...,t,109,t,0.91,t,120,f,?,other,P
3,70,F,t,f,f,f,f,f,f,f,...,t,175,f,?,f,?,f,?,other,P
4,70,F,f,f,f,f,f,f,f,f,...,t,61,t,0.87,t,70,f,?,SVI,P

In [66]:
df.replace('?', pd.NA, inplace=True)

In [68]:
df.isnull().sum()

age                             1
sex                           150
on thyroxine                    0
query on thyroxine              0
on antithyroid medication       0
sick                            0
pregnant                        0
thyroid surgery                 0
I131 treatment                  0
query hypothyroid               0
query hyperthyroid              0
lithium                         0
goitre                          0
tumor                           0
hypopituitary                   0
psych                           0
TSH measured                    0
TSH                           369
T3 measured                     0
T3                            769
TT4 measured                    0
TT4                           231
T4U measured                    0
T4U                           387
FTI measured                    0
FTI                           385
TBG measured                    0
TBG                          3772
referral source                 0
binaryClass                     0
dtype: int64

In [70]:
if 'TBG' in df.columns:
    df.drop(columns=['TBG'], inplace=True)

num_cols = ['age', 'TSH', 'T3', 'TT4', 'T4U', 'FTI']
for col in num_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

for col in num_cols:
    median_val = df[col].median()
    df[col].fillna(median_val, inplace=True)

print(df[num_cols].isnull().sum())

age    0
TSH    0
T3     0
TT4    0
T4U    0
FTI    0
dtype: int64

C:\Users\juded\AppData\Local\Temp\ipykernel_14744\4281100286.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(median_val, inplace=True)

In [72]:
for col in num_cols:
    median_val = df[col].median()
    df[col] = df[col].fillna(median_val)

In [74]:
keep_cols = [
    'age', 'sex',
    'on thyroxine', 'query on thyroxine', 'on antithyroid medication',
    'sick', 'pregnant', 'thyroid surgery', 'I131 treatment',
    'query hypothyroid', 'query hyperthyroid', 'lithium',
    'goitre', 'tumor', 'hypopituitary', 'psych',
    'TSH', 'T3', 'TT4', 'T4U', 'FTI',
    'binaryClass'
]
df = df[keep_cols]

In [76]:
# Convert sex: M = 0, F = 1
df['sex'] = df['sex'].map({'M': 0, 'F': 1})

# Convert all t/f to 1/0
bool_cols = [
    'on thyroxine', 'query on thyroxine', 'on antithyroid medication',
    'sick', 'pregnant', 'thyroid surgery', 'I131 treatment',
    'query hypothyroid', 'query hyperthyroid', 'lithium',
    'goitre', 'tumor', 'hypopituitary', 'psych'
]
for col in bool_cols:
    df[col] = df[col].map({'t': 1, 'f': 0})

# Convert target class: N = 0, P = 1
df['binaryClass'] = df['binaryClass'].map({'N': 0, 'P': 1})

In [77]:
for col in bool_cols:
    print(f"{col}: {df[col].unique()}")

on thyroxine: [nan]
query on thyroxine: [nan]
on antithyroid medication: [nan]
sick: [nan]
pregnant: [nan]
thyroid surgery: [nan]
I131 treatment: [nan]
query hypothyroid: [nan]
query hyperthyroid: [nan]
lithium: [nan]
goitre: [nan]
tumor: [nan]
hypopituitary: [nan]
psych: [nan]

In [79]:
df.replace('?', pd.NA, inplace=True)

In [81]:
numeric_cols = ['age', 'TSH', 'T3', 'TT4', 'T4U', 'FTI']
df[numeric_cols] = df[numeric_cols].astype(float)

In [84]:
for col in numeric_cols:
    median_val = df[col].median()
    df[col] = df[col].fillna(median_val)

In [86]:
bool_cols = df.columns[df.isin(['t', 'f']).any()]
df[bool_cols] = df[bool_cols].replace({'t': 1, 'f': 0})

In [87]:
df['binaryClass'] = df['binaryClass'].replace({'P': 1, 'N': 0})

In [89]:
print(df.columns.tolist())

['age', 'sex', 'on thyroxine', 'query on thyroxine', 'on antithyroid medication', 'sick', 'pregnant', 'thyroid surgery', 'I131 treatment', 'query hypothyroid', 'query hyperthyroid', 'lithium', 'goitre', 'tumor', 'hypopituitary', 'psych', 'TSH', 'T3', 'TT4', 'T4U', 'FTI', 'binaryClass']

In [96]:
import pandas as pd

# Step 1: Define column names
columns = ['age', 'sex', 'on thyroxine', 'query on thyroxine', 'on antithyroid medication', 'sick',
           'pregnant', 'thyroid surgery', 'I131 treatment', 'query hypothyroid', 'query hyperthyroid',
           'lithium', 'goitre', 'tumor', 'hypopituitary', 'psych', 'TSH measured', 'TSH',
           'T3 measured', 'T3', 'TT4 measured', 'TT4', 'T4U measured', 'T4U',
           'FTI measured', 'FTI', 'TBG measured', 'TBG', 'referral source', 'binaryClass']

# Step 2: Load CSV
df = pd.read_csv("../data/hypothyroid.csv", header=None, names=columns, skiprows=1)

# Step 3: Drop unneeded columns
df.drop(columns=['TSH measured', 'T3 measured', 'TT4 measured', 'T4U measured',
                 'FTI measured', 'TBG measured', 'TBG'], inplace=True)

# Step 4: Convert numeric columns to float and fill missing
numeric_cols = ['age', 'TSH', 'T3', 'TT4', 'T4U', 'FTI']
df[numeric_cols] = df[numeric_cols].apply(pd.to_numeric, errors='coerce')
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].median())

# Step 5: Convert boolean-like categorical columns (t/f) to 1/0
bool_cols = ['on thyroxine', 'query on thyroxine', 'on antithyroid medication', 'sick',
             'pregnant', 'thyroid surgery', 'I131 treatment', 'query hypothyroid',
             'query hyperthyroid', 'lithium', 'goitre', 'tumor', 'hypopituitary', 'psych']
df[bool_cols] = df[bool_cols].replace({'t': 1, 'f': 0}).infer_objects()

# Step 6: Encode 'sex'
df['sex'] = df['sex'].replace({'M': 1, 'F': 0})
df['sex'] = df['sex'].fillna(-1)

# Step 7: Handle target column
df['binaryClass'] = df['binaryClass'].replace({'P': 1, 'N': 0}).infer_objects()

# Step 8: Encode 'referral source'
df['referral source'] = df['referral source'].astype('category').cat.codes

# Final view
print(df.head())

    age sex  on thyroxine  query on thyroxine  on antithyroid medication  \
0  41.0   0             0                   0                          0
1  23.0   0             0                   0                          0
2  46.0   1             0                   0                          0
3  70.0   0             1                   0                          0
4  70.0   0             0                   0                          0

   sick  pregnant  thyroid surgery  I131 treatment  query hypothyroid  ...  \
0     0         0                0               0                  0  ...
1     0         0                0               0                  0  ...
2     0         0                0               0                  0  ...
3     0         0                0               0                  0  ...
4     0         0                0               0                  0  ...

   tumor  hypopituitary  psych   TSH   T3    TT4   T4U    FTI  \
0      0              0      0  1.30  2.5  125.0  1.14  109.0
1      0              0      0  4.10  2.0  102.0  0.98  107.0
2      0              0      0  0.98  2.0  109.0  0.91  120.0
3      0              0      0  0.16  1.9  175.0  0.98  107.0
4      0              0      0  0.72  1.2   61.0  0.87   70.0

   referral source  binaryClass
0                1            1
1                4            1
2                4            1
3                4            1
4                3            1

[5 rows x 23 columns]

C:\Users\juded\AppData\Local\Temp\ipykernel_14744\805750150.py:26: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[bool_cols] = df[bool_cols].replace({'t': 1, 'f': 0}).infer_objects()
C:\Users\juded\AppData\Local\Temp\ipykernel_14744\805750150.py:33: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['binaryClass'] = df['binaryClass'].replace({'P': 1, 'N': 0}).infer_objects()

In [97]:
df.to_csv("../data/thyroid_cleaned.csv", index=False)